default_config:
logger:
  default: error
  logs:
    custom_components.onebusaway: debug

sensor:
  - platform: onebusaway
    api_key: TEST
    name: onebusaway_admiral_59th_50
    stop: "1_14970"
    route: "1_100230"